/**
 * Canonical API error codes. Every error envelope carries one of these.
 * Mobile maps each code to a localized, user-friendly message
 * (see @masalim/localization `errors.*` keys); raw codes are never shown to users.
 */
export const ErrorCode = {
  // auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_PROVIDER_TOKEN_INVALID: 'AUTH_PROVIDER_TOKEN_INVALID',
  AUTH_RESET_CODE_INVALID: 'AUTH_RESET_CODE_INVALID',
  AUTH_LOCKED_OUT: 'AUTH_LOCKED_OUT',

  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN_OWNERSHIP: 'FORBIDDEN_OWNERSHIP',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  APP_VERSION_UNSUPPORTED: 'APP_VERSION_UNSUPPORTED',
  INTERNAL: 'INTERNAL',

  // entitlements
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',

  // stories
  STORY_GENERATION_FAILED: 'STORY_GENERATION_FAILED',
  MODERATION_REJECTED: 'MODERATION_REJECTED',
  STORY_NOT_READY: 'STORY_NOT_READY',

  // voice
  VOICE_CONSENT_REQUIRED: 'VOICE_CONSENT_REQUIRED',
  VOICE_PROCESSING_FAILED: 'VOICE_PROCESSING_FAILED',
  VOICE_NOT_READY: 'VOICE_NOT_READY',
  RECORDING_TOO_SHORT: 'RECORDING_TOO_SHORT',
  RECORDING_TOO_LONG: 'RECORDING_TOO_LONG',
  RECORDING_QUALITY_LOW: 'RECORDING_QUALITY_LOW',

  // media / uploads
  UPLOAD_TYPE_INVALID: 'UPLOAD_TYPE_INVALID',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  TTS_FAILED: 'TTS_FAILED',
  ILLUSTRATION_FAILED: 'ILLUSTRATION_FAILED',
  BOOK_RENDER_FAILED: 'BOOK_RENDER_FAILED',

  // commerce
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    requestId?: string;
    details?: unknown;
  };
}
